@startuml
sprite $efesto_kafka [159x232/16z] {
xDX7LiH060FXadwJLhh_QSdGp8eCclVwspgLiztv7TksRTksRTksYTGwU91Al6XkCzJMwJ8IfCZO1-kakYeF2tdL9O3J0WJ3QHu5OG9y2Kbc1d2IcA8yGHuC
W0Ae9OzdBwbB6hnjQMjRJPFaKXXWIh9Eym1bwSWR7iG2vDGmE8TXvK5NdW-peeoS7ZZBoci5DBVHspSqzyseE6zcU69NvWL1_zKdfHG6FEbq0mOxdGOCa5A0
mEapCubueFIHbAHvQELSygRrv4OIa3gsamIf_vilhK2zUVq7ZnGRaMOpgTNFJZD8iGCvnOmdlOIT3nc1VUHFZQHy10ziWFmT0n-T3vG__Zxyu8-axvYr2oJ9
TI08mtzcQXbq_zC-g90LjZKKqEh9fO66prHRKp8WcDdsNyM7UBOmC97A8tKdaFK-xmJRC9Vn6IIzfqEJTGRkuTbvsyUC0V01tS1RFblZiquRUDTIz_QK89wy
1XNfiJpW_fbGk-mktqQyakq2wk759Kav_1PF1JXGuAG1vk4yJzuR4L0yYmx4zKKzd9SaxpNo4NLIDjlkqgZUsSFxK0UWDXyUvC-qF2q1Fmf4RKrwnO973ynZ
FhBt61_fKiKPGFU71Lf_Cox3_CXPLXlS7nSI-wspaihuI2YNfNu3Zp-vtk4f4thmzFMusM_7yAUzVUeLzdGTWA1uhUqPdRrUzGHLlSqyq1a7TSzIGnCe-6LU
84cLv8Ddos1G-ex0l48NNeClnOjXxcZlhSW1PAzk-gYxALuHw-lUvwlyi1qdTvuJfqu17xm15MIVpnQnPLzvTg6Dk6RpJ3KYmC8RfTjS8ZzXvWjuLkPnxcbK
wQ9V6gasVFipUK0VFba2wTmdiD-ry6P09rs9ynIUFSwjsDq3aIGN7S1pUJqftaY4hqtLKmzkyLxB5y1vugNXse_3_4OplJt5urlLknwBpyPBXpP6Qwyf0BQp
Zcl3BeBh4ETJyIITPrT9FiM2GvBxVYcenGarFvQzdpTyutDg3ubfYhJCtNO7sOEdLDFlhECFdjSLJ9vTdyEdk3PMWcsx2-T-3KkmLxVuHfll1kJ60yYJr-rB
P7SRUpsu_WntqTbZCANpu2VUoqlibtq5NETIaFsyjFgijJCF3j_2svon3u_Q4fycKcD4DIAbxuyDdZnxxQBE1tv_F9hHkLAwyfv_DzMOozkUZLQ_ye1dykgq
Sn8pe1TUlC-tDaYZYgHfeBvGgL9TiRRniiuK1o-nuRoCjP-7JhnZEEkqwoe8nKlEq-azKzoXcxoCNlxSBWZGxMdQmFi2mAg-yWImj-Nx-FiKZw_tfwdlo8VU
vnSiMvNjHUzi0C-lBPKnWYzxccJFFP7p9JmNcQq464thpiAI7Cqb6RmXC83elHciKLQIdLT6R5iz11B1d8rzDHKDw9rdRUA9yUFYcHSXYiTfLoLPrZGV6Ryo
XehWjzORLxwqjhDZgKCBRcqfXUFlhqDtGm7Pmckzou03M5mphFWufDewPFdgW-1mYU0m0CkaQ82thOi3Ay-t6Z8x1TXqwxq596QDqb_ZjVzLLR8J0ItHlytS
YMx3jXf4uJFpqtTjE-__jDqC10mP2bP4DJvOit-G5KAYIFk-0oWpPxFWLU7gUG6CwwOvHuavTRpXXGIdqWK2YyVUc-vdM30dw7dzQbDNXhHx1Ku39n7qFDCt
yZuUhPf_PGeGtkUpAR5EonjmWCmLY7faJsKg2LtzXrhpIgir8o2KZV6Ho8ky_5_8NcxyLTt0W-uq1rNLmT94Gxxi8K3j9bvP021NZLUlXPo_0ochdhpAZX1T
LO9d-ZHs0wIGB7Xb_jjcno9In5JFG-APP8m4hrnK0LpYjQeaEkO1uiE7012GRFMDbVGyXgnQVL42rNtxC06muFcHrZgno2_EVdsRfyepMsUE7HYuSnkh1VJF
fqxfK7kygYFNaco-wlYa_6Tu9PGg6pHUIwrvoajnaOTj4jkEw7b9hXuzuFh8uYGsT1P9kSupe2iybzNluW26Qrw-vskjG0Rhsxncs-dJ8I_HYoUVPGDEp3Tv
e047200-7iOt0yy6ROvv-D9iHnCml1fZIPMNmqnUwNz0piVuNC8sKsabTHzociS5tgUp435dYqNtZdgFriQR0-OaNkNPiEyzBUoM61jRd6yO0U8oW-o2hge0
OVEzEfp6XUs-e1ike7nDLtQ9prCQw28kmoNbTtKDFtdpRmvNvyngmfxZMK9Ers-RTdG0_syp3mbchhwwc99Af4litOLLDUfGWSSxj_dZzgYIAbtTgN8VZpIW
XRvyzZsQSSqsu9PtEnae28-Vgt9L0pyiLBZkVYFuzXKlIKhI-ewZD3pP7t2tyn89QSMR3viWDyPyZOcN8_ziSsvDcYbCd-i_Q3oJKUvEcWwVXYCgzICZwgYt
z9ZFeVNCGCHSxcjSvil9LFage6L7vNGXJhQSjVdtzcENo5jy5jonzx-A7Rn8kOE7lCDdL-u8cGq-QBkMNtnAhbpdLTKzF532q3pYwTXNhkoesfVZ5KDI4khL
IGn9tBf4JWDll6CzvW7tyLZTFlF23DNTFBt2uyUEdb6jU4C_mGkknQd5gjp3gwgC5QfPSfPdtyGJ94oTUwwnXvVA510uvLkCJdV4YiUIbpdWNzdVlmG4JlcM
gmUsnx8rR_MBLBl_DHu0EV19cd5BtsCpZwEabAjzMkf0Lbd0Nfu5pW4FI2800L9MDI5W9m_0_mzTwJzIFqqGo47D5i0-tkmPrr0Xv-N4TfuFUK1UZxqymCun
BoVo5jweo_BSarlEj9DNuCh4GtpaoeyTFQJACnQPSpm1shFB-W5E3dskd0putnqxcFRm0BAZ6YRZz5uy0Uc3kPoiX6_QFBT1b_9jl5pNeSgc_WLaRq1bL-1i
hI3RidXaPxQoBI1RApi_mdDLkNAKKVqx--8KJxQfvTiMDI7Lpvqe0h0iLLUIGcKAihSgdnqo1CXz7xoyGGAiOL4roWqXvtqJVcSUSikcze-PbYllLFlCgt_b
lR9JbJVkWmTvnvhXtNcWoe_q1m
}
@enduml
