@startuml
sprite $kafka [232x232/16z] {
xTtRThEy5KRXkPQTTbYDcFT_jptfpWK-P9pVi1m_nsGCNYGJeQtZFYRr4ip4LUs-2TGaMPGgxn8p-8DKBAyfmPzafDtYKBQbKh_EZj1cNTWPP678k6-hQYRZ
mhg2Nn4qU8nO4GyphITvM1VBOGUxjJJP8yHYWZsiXRMO6QhwzIxlN9PSxgw8yWMAbv66G5J_XU9OKPKlK6EaeB1spfIvqTTLbAwsWJWp5IzGcJ57dqZfd5_Y
ebut9n9mJuOVIHPk38LPD-Sd9zpB55VyBRdtzxevIST_dr6utbx45LauvoEjyoZx-qnpl8TheUmhZpR8SCueb3F66ws_edqxIU6S6CDt7oJtgdz_CdHXf6NW
DKS-GDChCxrwBtNAo2YmGw1DwjHWyZ1fi42PL5KRci6Sanl0U-1HEdCHAYGagC62tCgPglQ89CZCgwhPppLYlpNC54wRAPDxGQhf8LWHa4GGBBgAwr095XsJ
59CLkNkyh2kh4frg3FCIo1DJhhGL6HWqNTVP455bVWBFFZSFq7dGJrGFvUmrDyLbap8eNX-q6pzMQncdd7eoXepMZDEzTZ6VdsaYyXXVhaaon3RmKJ0epZi3
LmO-PeTTVBccR4WKrvMPXdG9_Y1oeA-fHb1pPqgHNSA3nDu7ppxUFC2aBXVbj3Fcm0M709KxAirTELLehO5wjZdBtHrtmW8b_RVaVFFA7f-QUHremAu5RHva
HtaEDL-Rdck6Q_n0JltMaQ1QfpmpngeZCkUjJ4vc7hcKzyl9BycPCcFMpVdGjUqDStPFjEWd_hgSxKmJEdYZd9_oJ0UwfVVcz4o_puS_-MCqwCqyoVjsWhZF
2RWX2hKJkagm8bGdL-HepdPqJbI2TH6ekEZ2p43C0tAYa6nHXYjk3ZRxNfio6T9NaiPGCU6X_GcfJmtdfGvTY8TMMxmoBhvavFP1O-Gwko_2k7bDGpFOdYlK
zE2EwdXkiE3AEbNx7n-dxQmn8Hsl36VfZcUNNG_fi5_dfEmJYl8qNuJTDAD8pYO7ynKmETRL5y3WO7xx2XpCs--8QT6ODwtsBoLtF0rLAyNSLV8FFXWFpwdt
xuURoXRj_xwQ4RRZO-RZt-7QnYy6JL-Y-rW743hSnT1EjDvX8EPmKCssuwcyGlfmVKeTl-tioZ8rVHsMT7F7ircKgelNedhihzEcEuAcIrh_tvtnKbLxEy4g
mPsrmEP9jNqvaIMU60js_rtnuXmlq5lbtGdt5sZzd5agv_wxfLJEDZISKpzdbxdmvgPRgPpwnCr-SfxB9-VqRZadWvd9xgPMlvrmTN8Jnkze3vNAkVzkaLev
SzVTJh8Wd3xVPP_lx1V80_jDFlrWnVirxnzYK_qL_TIflisuWyeo5VKpZlHMuuAfdt7USu_RVwjgzv2fGvzv68xTnrVrUJNourIe7dI_Jz1RWLd6TUQb8WVx
rfEKwESdgbzbWdPb9qqjLA2oYtPLUPRzp44BhhlIfsBgreMzQzzOHrTWNMGgb5WNcJwtEtMMMUVwvBfb2gnRVZIefWkei0vTJNqYfR9_Nu7qbPhA1hMvY2hx
HAZVQcULQdS59VRzkCU2tx7Vc_vOpc_RQGQYa3j_-JvBtoSfJtx9FcYVd9-SQsxbSzRVTv9Vieye7j1Eg9tJ-ZdtxzlSo-IK6RrLsuUR7zfN_QRCIQMS1VV9
Zu6SvSyzQ3z_ZaMsFDiv5jzg3lGbp4MrSqb-nJapkuUsRdxLEJSedxWdZ18ncx8bwf_hXS-Uuufn_fpDO4JywBbxUShIh7-EOZCEE1SpTFAL9ZDvUT1GV2qU
a-8gHYcbpo7EinxcQl0eUJ9e-7hiOBgEJUdhTNOeT-uxnkwS-vA6XqYM911voM15tmeg13CHAdgEuanYwosLJlv9gbVYFYIfffxbrnag92Ii9UrERYRLl41a
G5nLpSa3f9l_mYVq2dbVcaEhii5xu34cHvexs7U_Jg1DwjJWT1j6CB9XTtJBI9cJeGipB8FnyvlcGSD2Oh15DotKNAl07kCtNpddbV_d6rRSNAgCEPppKler
nEXFEQDmpdpFd8pdNBYsSCwBZ9_iNhZUXZd-lYsVy_thBJAS4-iO-5gfLsttBpkHqZbnS3oisPaf_lqvkkhaOYN1ZDD8kMCXo502AFuQClVkLtCHAs59RW-d
MGgouajLBy6Y56jXJK2mncAQx29M4ppEPZbN7jP5Vq61cbPqm8-pGebQLFCVlo6cOZ1iiYwSWZ6MXZ94M_MWmJR5sfecVnRfD5aUEbAOzQ4cArB5Dz6NaqPS
rCbtSxtxyWmyaNy2
}

@enduml