@startuml

!include https://raw.githubusercontent.com/gitgabrio/drools/efesto_communication_layer/efesto/documentation/puml/puml_images/Images.puml

!include kafka.puml
!include efesto_kafka.puml


@enduml